"""关联班级、培养方案表

Revision ID: 03b6345edd92
Revises: e361b94db4e0
Create Date: 2022-02-24 20:30:49.874039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b6345edd92'
down_revision = 'e361b94db4e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade_class', sa.Column('plan_teaching_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'grade_class', 'plan_teaching', ['plan_teaching_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grade_class', type_='foreignkey')
    op.drop_column('grade_class', 'plan_teaching_id')
    # ### end Alembic commands ###
