"""培养方案表新增学分字段

Revision ID: 1ab04a711929
Revises: 8a441b2f6030
Create Date: 2022-02-24 20:53:07.035059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab04a711929'
down_revision = '8a441b2f6030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_teaching', sa.Column('credit', sa.Text(length=108000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_teaching', 'credit')
    # ### end Alembic commands ###
