"""新增教学计划，培养方案

Revision ID: 6dd4e929bd5a
Revises: b7608f3c5215
Create Date: 2022-02-20 17:26:15.137393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd4e929bd5a'
down_revision = 'b7608f3c5215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_teaching',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('code', sa.String(length=256), nullable=True),
    sa.Column('major_id', sa.Integer(), nullable=True),
    sa.Column('education_system', sa.String(length=256), nullable=True),
    sa.Column('prospective_student', sa.String(length=256), nullable=True),
    sa.Column('fields', sa.String(length=1080), nullable=True),
    sa.Column('professions', sa.String(length=1080), nullable=True),
    sa.Column('content', sa.Text(length=108000), nullable=True),
    sa.ForeignKeyConstraint(['major_id'], ['base_major.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_teaching')
    # ### end Alembic commands ###
