"""新增教学计划，培养方案

Revision ID: 7385e01b2621
Revises: 6dd4e929bd5a
Create Date: 2022-02-20 18:13:33.164621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7385e01b2621'
down_revision = '6dd4e929bd5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_teaching', sa.Column('plan', sa.Text(length=108000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_teaching', 'plan')
    # ### end Alembic commands ###
