"""班级表新增当前学期字段

Revision ID: 8a441b2f6030
Revises: 03b6345edd92
Create Date: 2022-02-24 20:45:09.583792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a441b2f6030'
down_revision = '03b6345edd92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade_class', sa.Column('current_term', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grade_class', 'current_term')
    # ### end Alembic commands ###
