"""新增班级的学生

Revision ID: b1ac2a80e230
Revises: 7385e01b2621
Create Date: 2022-02-21 11:24:47.573987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ac2a80e230'
down_revision = '7385e01b2621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'grade_class', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'class_id')
    # ### end Alembic commands ###
