"""'修改选课状态为字符串'

Revision ID: c9671d1dc74a
Revises: 1ab04a711929
Create Date: 2022-03-05 17:57:06.563602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9671d1dc74a'
down_revision = '1ab04a711929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_major', 'total_credict')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_major', sa.Column('total_credict', mysql.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
