"""删除实际人数

Revision ID: e361b94db4e0
Revises: b1ac2a80e230
Create Date: 2022-02-23 00:25:36.555993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e361b94db4e0'
down_revision = 'b1ac2a80e230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_course_scheduling', 'actual_members')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_course_scheduling', sa.Column('actual_members', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
