version: '2'

services:

    tms-flask:
        container_name: tms-flask
        command: gunicorn -w 4 -b 0.0.0.0:5000 -t 160 manage:app
        #  --log-level DEBUG
        build: ./server
        image: tms_server_flask
        ports:
            - "5000:5000"
        volumes:
            - ./server:/home/server

        networks:
            - public-container
        environment:
            - PYTHONUNBUFFERED=0
        restart: always
networks:
  public-container:
    external: true